[package]
name = "rust_fetch"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = "0.30.12"
colored = "2.1.0"
indexmap = "2.2.6"
regex = "1.10.5"
pad = "0.1.6"

[dev-dependencies]
cargo-run = "0.4.0"

[project.authors]
name = "Hazel Thomas"
name = "SurgeDevs"
